// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentExam.Infrastructure.Persistence;

#nullable disable

namespace StudentExam.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903210251_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentExam.Domain.Entities.Course", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(3)");

                    b.Property<byte>("ClassLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TeacherFirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TeacherLastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Code");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("StudentExam.Domain.Entities.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date");

                    b.Property<byte>("Score")
                        .HasColumnType("tinyint");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseCode");

                    b.HasIndex("StudentNumber");

                    b.ToTable("Exams", t =>
                        {
                            t.HasCheckConstraint("CK_Exam_Score_Range", "[Score] BETWEEN 0 AND 9");
                        });
                });

            modelBuilder.Entity("StudentExam.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<byte>("ClassLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Number");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentExam.Domain.Entities.Exam", b =>
                {
                    b.HasOne("StudentExam.Domain.Entities.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentExam.Domain.Entities.Student", "Student")
                        .WithMany("Exams")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentExam.Domain.Entities.Course", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("StudentExam.Domain.Entities.Student", b =>
                {
                    b.Navigation("Exams");
                });
#pragma warning restore 612, 618
        }
    }
}
